# Generated by Django 5.1.1 on 2024-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_user_trial_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_calls',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
