# Generated by Django 5.1.1 on 2024-09-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_user_trial_calls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trial_calls',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
