# Generated by Django 5.1.1 on 2024-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0004_alter_user_trial_calls'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend_base_url', models.URLField(max_length=255, verbose_name='Backend Base URL')),
                ('frontend_base_url', models.URLField(max_length=255, verbose_name='Frontend Base URL')),
                ('site_name', models.CharField(default='My Website', max_length=255, verbose_name='Site Name')),
                ('contact_email', models.EmailField(default='support@example.com', max_length=254, verbose_name='Contact Email')),
            ],
            options={
                'verbose_name': 'Global Setting',
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
