# Generated by Django 5.1.1 on 2024-09-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0005_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='payment_page_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Payment Page URL'),
        ),
    ]
