# Generated by Django 5.1.1 on 2024-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0006_globalsettings_payment_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='cbt_api_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='CBT API Token'),
        ),
    ]
