# Generated by Django 5.1.1 on 2024-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0007_globalsettings_cbt_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
