# Generated by Django 5.1.1 on 2024-09-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0008_user_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
