# Generated by Django 5.1.1 on 2024-11-02 19:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0009_alter_user_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='payment_page_url',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='subscription_price',
            field=models.DecimalField(decimal_places=2, help_text='Price in NGN', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Subscription Price'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
