# Generated by Django 5.1.1 on 2025-01-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0010_remove_globalsettings_payment_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
